CREATE TABLE IF NOT EXISTS USERS (
   USER_ID INT PRIMARY KEY AUTO_INCREMENT,
   EMAIL VARCHAR(50) NOT NULL,
   LOGIN VARCHAR(50) NOT NULL,
   USER_NAME VARCHAR(50) NOT NULL,
   BIRTHDAY DATE
);

CREATE TABLE IF NOT EXISTS MPA (
    MPA_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    MPA_NAME VARCHAR(50) NOT NULL,
    CONSTRAINT MPA_PK PRIMARY KEY (MPA_ID)
);

CREATE TABLE IF NOT EXISTS USER_FRIENDS (
    USER_ID INT NOT NULL,
    FRIEND_ID INT NOT NULL,
    FRIEND_STATUS BOOLEAN,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    FOREIGN KEY (FRIEND_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS FILMS (
    FILM_ID INT PRIMARY KEY AUTO_INCREMENT,
    FILM_NAME VARCHAR(50) NOT NULL,
    RELEASEDATE DATE NOT NULL,
    DESCRIPTION VARCHAR(200) NOT NULL,
    DURATION INT NOT NULL,
    RATE INT
);

CREATE TABLE IF NOT EXISTS FILM_LIKES (
    FILM_ID INT NOT NULL,
    USER_ID INT NOT NULL
);

CREATE TABLE IF NOT EXISTS GENRES (
    GENRE_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    GENRE_NAME VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS FILM_GENRES (
   FILM_ID INT NOT NULL,
   GENRE_ID INT NOT NULL
);

CREATE TABLE IF NOT EXISTS FILM_MPA(
    FILM_ID INT NOT NULL,
    MPA_ID INT NOT NULL
)

